// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoergyvppqhvjzeqgdzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZXJneXZwcHFodmp6ZXFnZHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTQ5OTAsImV4cCI6MjA2NDk5MDk5MH0.s0iBrGPvn5siKq98xrWBNvtqIYEZXlxP22nKOozaBM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);